{% set name = "pydruglogics" %}
{% set version = "0.1.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - joblib >=1.4.2
    - matplotlib >=3.9.2
    - mpbn >=3.8
    - numpy >=2.1.3
    - pandas >=2.2.3
    - pygad >=3.3.1
    - scikit-learn >=1.5.2
    - scipy >=1.14.1
    - colomoto::pyboolnet >=3.0.13

test:
  imports:
    - pydruglogics

about:
  home: https://github.com/druglogics/pydruglogics
  license: GPL-3.0
  license_file: LICENSE
  summary: "PyDrugLogics: A Python package for constructing, optimizing Boolean Models, and performing in-silico perturbations."
  description: |
    PyDrugLogics is a Python package designed for constructing and optimizing Boolean models, enabling in-silico perturbation analysis.
  doc_url: https://druglogics.github.io/pydruglogics/
  dev_url: https://github.com/druglogics/pydruglogics

extra:
  recipe-maintainers:
    - szlaura
