{% set name = "pydruglogics" %}
{% set version = environ.get('VERSION', '0.1.6') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/{{ name }}/pydruglogics-{{ version }}.tar.gz

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
  run:
    - python >=3.11
    - joblib
    - matplotlib
    - colomoto::mpbn >=3.8
    - numpy
    - pandas
    - conda-forge::pygad
    - scikit-learn
    - scipy
    - colomoto::pyboolnet >=3.0.13

test:
  imports:
    - pydruglogics

about:
  home: https://github.com/druglogics/pydruglogics
  license: GPL-3.0
  license_file: LICENSE
  summary: "PyDrugLogics: A Python package for constructing, optimizing Boolean Models, and performing in-silico perturbations."
  description: |
    PyDrugLogics is a Python package designed for constructing and optimizing Boolean models, enabling in-silico perturbation analysis.
  doc_url: https://druglogics.github.io/pydruglogics/
  dev_url: https://github.com/druglogics/pydruglogics
