name: PyPI Release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Extract version from tag and update files
     run: |
       set -e
       sed -i "s:9999:${VERSION//*v/}:" setup.py conda/meta.yaml
       echo "Version set successfully in setup.py and conda/meta.yaml"
     env:
       VERSION: ${{ github.ref }}

   - name: Set up Python
     uses: actions/setup-python@v4
     with:
       python-version: '3.11'

   - name: Install PyPI dependencies
     run: |
       set -e
       python -m pip install --upgrade pip setuptools wheel twine

   - name: Build and publish to PyPI
     env:
       TWINE_USERNAME: __token__
       TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
     run: |
       set -e
       python setup.py sdist bdist_wheel
       twine upload dist/*