name: Conda Release

on:
  workflow_run:
    workflows: ["PyPI Release"]
    types:
      - completed

jobs:
  conda-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conda environment
        uses: s-weigand/setup-conda@v1
        with:
          python-version: '3.11'

      - name: Install Conda dependencies
        run: |
          set -e
          conda install -y anaconda-client conda-build conda-verify conda-libmamba-solver
          conda config --set solver libmamba
          conda config --set channel_priority flexible

      - name: Build Conda package
        run: |
          set -e
          cd conda
          conda build --user szlaura --token $ANACONDA_API_TOKEN --override-channels -c defaults -c conda-forge -c colomoto .
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}